// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SC01_SquareLine

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_ContainerKeyboard;
lv_obj_t *ui_ButtonKeyboard1;
lv_obj_t *ui_LabelButtonKeyboard1;
lv_obj_t *ui_ButtonKeyboard2;
lv_obj_t *ui_LabelButtonKeyboard2;
lv_obj_t *ui_ButtonKeyboard3;
lv_obj_t *ui_LabelButtonKeyboard3;
lv_obj_t *ui_ButtonKeyboard4;
lv_obj_t *ui_LabelButtonKeyboard4;
lv_obj_t *ui_ButtonKeyboard5;
lv_obj_t *ui_LabelButtonKeyboard5;
lv_obj_t *ui_ButtonKeyboard6;
lv_obj_t *ui_LabelButtonKeyboard6;
lv_obj_t *ui_ButtonKeyboard7;
lv_obj_t *ui_LabelButtonKeyboard7;
lv_obj_t *ui_ButtonKeyboard8;
lv_obj_t *ui_LabelButtonKeyboard8;
lv_obj_t *ui_ButtonKeyboard9;
lv_obj_t *ui_LabelButtonKeyboard9;
lv_obj_t *ui_ButtonKeyboard10;
lv_obj_t *ui_LabelButtonKeyboard10;
lv_obj_t *ui_ButtonKeyboard11;
lv_obj_t *ui_LabelButtonKeyboard11;
lv_obj_t *ui_ButtonKeyboard12;
lv_obj_t *ui_LabelButtonKeyboard12;
lv_obj_t *ui_ContainerSelectTop;
lv_obj_t *ui_ButtonTop1;
lv_obj_t *ui_LabelButtonTop1;
lv_obj_t *ui_ButtonTop2;
lv_obj_t *ui_LabelButtonTop2;
lv_obj_t *ui_ButtonTop3;
lv_obj_t *ui_LabelButtonTop3;
lv_obj_t *ui_ButtonTop4;
lv_obj_t *ui_LabelButtonTop4;
lv_obj_t *ui_ContainerChannel;
lv_obj_t *ui_ButtonChannel1;
lv_obj_t *ui_LabelChannel1;
lv_obj_t *ui_ButtonChannel2;
lv_obj_t *ui_LabelChannel2;
lv_obj_t *ui_ButtonChannel3;
lv_obj_t *ui_LabelChannel3;
lv_obj_t *ui_ButtonChannel4;
lv_obj_t *ui_LabelChannel4;
lv_obj_t *ui_ButtonChannel5;
lv_obj_t *ui_LabelChannel5;
lv_obj_t *ui_ButtonChannel6;
lv_obj_t *ui_LabelChannel6;
lv_obj_t *ui_ButtonChannel7;
lv_obj_t *ui_LabelChannel7;
lv_obj_t *ui_ButtonChannel8;
lv_obj_t *ui_LabelChannel8;
lv_obj_t *ui_ButtonChannel9;
lv_obj_t *ui_LabelChannel9;
lv_obj_t *ui_ButtonChannel10;
lv_obj_t *ui_LabelChannel10;
lv_obj_t *ui_ButtonChannel11;
lv_obj_t *ui_LabelChannel11;
lv_obj_t *ui_ButtonChannel12;
lv_obj_t *ui_LabelChannel12;
lv_obj_t *ui_ButtonChannel13;
lv_obj_t *ui_LabelChannel13;
lv_obj_t *ui_ButtonChannel14;
lv_obj_t *ui_LabelChannel14;
lv_obj_t *ui_ButtonChannel15;
lv_obj_t *ui_LabelChannel15;
lv_obj_t *ui_ButtonChannel16;
lv_obj_t *ui_LabelChannel16;
lv_obj_t *ui_ContainerSelectLayer;
lv_obj_t *ui_ButtonLayer1;
lv_obj_t *ui_LabelButtonLayer1;
lv_obj_t *ui_ButtonLayer2;
lv_obj_t *ui_LabelButtonLayer2;
lv_obj_t *ui_ButtonLayer3;
lv_obj_t *ui_LabelButtonLayer3;
lv_obj_t *ui_ButtonLayer4;
lv_obj_t *ui_LabelButtonLayer4;
lv_obj_t *ui_ContainerCCPage;
lv_obj_t *ui_ButtonPage1;
lv_obj_t *ui_LabelPage1;
lv_obj_t *ui_ButtonPage2;
lv_obj_t *ui_LabelPage2;
lv_obj_t *ui_ButtonPage3;
lv_obj_t *ui_LabelPage3;
lv_obj_t *ui_ButtonPage4;
lv_obj_t *ui_LabelPage4;
lv_obj_t *ui_ButtonPage5;
lv_obj_t *ui_LabelPage5;
lv_obj_t *ui_ButtonPage6;
lv_obj_t *ui_LabelPage6;
lv_obj_t *ui_ButtonPage7;
lv_obj_t *ui_LabelPage7;
lv_obj_t *ui_ButtonPage8;
lv_obj_t *ui_LabelPage8;
lv_obj_t *ui_Container4Enc;
void ui_event_Arc17( lv_event_t * e);
lv_obj_t *ui_Arc17;
lv_obj_t *ui_LabelValue17;
lv_obj_t *ui_LabelPot17;
void ui_event_Arc18( lv_event_t * e);
lv_obj_t *ui_Arc18;
lv_obj_t *ui_LabelValue18;
lv_obj_t *ui_LabelPot18;
void ui_event_Arc19( lv_event_t * e);
lv_obj_t *ui_Arc19;
lv_obj_t *ui_LabelValue19;
lv_obj_t *ui_LabelPot19;
void ui_event_Arc20( lv_event_t * e);
lv_obj_t *ui_Arc20;
lv_obj_t *ui_LabelPot20;
lv_obj_t *ui_LabelValue20;
void ui_event_ContainerRowBottom( lv_event_t * e);
lv_obj_t *ui_ContainerRowBottom;
void ui_event_SwitchLFOCC( lv_event_t * e);
lv_obj_t *ui_SwitchLFOCC;
lv_obj_t *ui_LabelSwitchLFOCC1;
lv_obj_t *ui_ButtonLFO1;
lv_obj_t *ui_ButtonSettings1;
lv_obj_t *ui_LabelButtonSettings1;
lv_obj_t *ui_ButtonLFO2;
lv_obj_t *ui_ButtonSettings2;
lv_obj_t *ui_LabelButtonSettings2;
lv_obj_t *ui_ButtonLFO3;
lv_obj_t *ui_ButtonSettings3;
lv_obj_t *ui_LabelButtonSettings3;
lv_obj_t *ui_ButtonLFO4;
lv_obj_t *ui_ButtonSettings4;
lv_obj_t *ui_LabelButtonSettings4;
lv_obj_t *ui_LabelKillLFO;
lv_obj_t *ui_SwitchKillLFO;
void ui_event_RollerSettings( lv_event_t * e);
lv_obj_t *ui_RollerSettings;
lv_obj_t *ui_ButtonLFOMix;
lv_obj_t *ui_LabelButtonLFOMix;
lv_obj_t *ui_ContainerSelect;
lv_obj_t *ui_ButtonGeneral1;
lv_obj_t *ui_LabelButtonGeneral1;
lv_obj_t *ui_ButtonGeneral2;
lv_obj_t *ui_LabelButtonGeneral2;
lv_obj_t *ui_ButtonGeneral3;
lv_obj_t *ui_LabelButtonGeneral3;
lv_obj_t *ui_ButtonGeneral4;
lv_obj_t *ui_LabelButtonGeneral4;
lv_obj_t *ui_ContainerDisplay;
lv_obj_t *ui_LFODisplay;
lv_obj_t *ui_LabelVibration;
lv_obj_t *ui_SwitchVibration;
lv_obj_t *ui_LabelDisplay3;
lv_obj_t *ui_LabelDisplay4;
lv_obj_t *ui_ContainerPots1;
lv_obj_t *ui_PanelKeyboard;
lv_obj_t *ui_WifiRoller;
lv_obj_t *ui_Keyboard1;
lv_obj_t *ui_TextArea1;
lv_obj_t *ui_EditLabel;
lv_obj_t *ui_ButtonWifi;
lv_obj_t *ui_LabelWifi;
void ui_event_PanelStats( lv_event_t * e);
lv_obj_t *ui_PanelStats;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Arc17( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_LabelValue17, target, "", "");
}
}

void ui_event_Arc18( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_LabelValue18, target, "", "");
}
}

void ui_event_Arc19( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_LabelValue19, target, "", "");
}
}

void ui_event_Arc20( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_LabelValue20, target, "", "");
}
}

void ui_event_ContainerRowBottom( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_flag_modify( ui_ContainerRowBottom, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SwitchLFOCC( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_flag_modify( ui_ContainerDisplay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

void ui_event_RollerSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_flag_modify( ui_ContainerCCPage, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_ContainerChannel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
      _ui_flag_modify( ui_ContainerDisplay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_ContainerCCPage, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_ContainerChannel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_ContainerDisplay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_PanelStats( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_PanelKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
