// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SC01_SquareLine

#ifndef _SC01_SQUARELINE_UI_H
#define _SC01_SQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_ContainerKeyboard;
extern lv_obj_t *ui_ButtonKeyboard1;
extern lv_obj_t *ui_LabelButtonKeyboard1;
extern lv_obj_t *ui_ButtonKeyboard2;
extern lv_obj_t *ui_LabelButtonKeyboard2;
extern lv_obj_t *ui_ButtonKeyboard3;
extern lv_obj_t *ui_LabelButtonKeyboard3;
extern lv_obj_t *ui_ButtonKeyboard4;
extern lv_obj_t *ui_LabelButtonKeyboard4;
extern lv_obj_t *ui_ButtonKeyboard5;
extern lv_obj_t *ui_LabelButtonKeyboard5;
extern lv_obj_t *ui_ButtonKeyboard6;
extern lv_obj_t *ui_LabelButtonKeyboard6;
extern lv_obj_t *ui_ButtonKeyboard7;
extern lv_obj_t *ui_LabelButtonKeyboard7;
extern lv_obj_t *ui_ButtonKeyboard8;
extern lv_obj_t *ui_LabelButtonKeyboard8;
extern lv_obj_t *ui_ButtonKeyboard9;
extern lv_obj_t *ui_LabelButtonKeyboard9;
extern lv_obj_t *ui_ButtonKeyboard10;
extern lv_obj_t *ui_LabelButtonKeyboard10;
extern lv_obj_t *ui_ButtonKeyboard11;
extern lv_obj_t *ui_LabelButtonKeyboard11;
extern lv_obj_t *ui_ButtonKeyboard12;
extern lv_obj_t *ui_LabelButtonKeyboard12;
extern lv_obj_t *ui_ContainerSelectTop;
extern lv_obj_t *ui_ButtonTop1;
extern lv_obj_t *ui_LabelButtonTop1;
extern lv_obj_t *ui_ButtonTop2;
extern lv_obj_t *ui_LabelButtonTop2;
extern lv_obj_t *ui_ButtonTop3;
extern lv_obj_t *ui_LabelButtonTop3;
extern lv_obj_t *ui_ButtonTop4;
extern lv_obj_t *ui_LabelButtonTop4;
extern lv_obj_t *ui_ContainerChannel;
extern lv_obj_t *ui_ButtonChannel1;
extern lv_obj_t *ui_LabelChannel1;
extern lv_obj_t *ui_ButtonChannel2;
extern lv_obj_t *ui_LabelChannel2;
extern lv_obj_t *ui_ButtonChannel3;
extern lv_obj_t *ui_LabelChannel3;
extern lv_obj_t *ui_ButtonChannel4;
extern lv_obj_t *ui_LabelChannel4;
extern lv_obj_t *ui_ButtonChannel5;
extern lv_obj_t *ui_LabelChannel5;
extern lv_obj_t *ui_ButtonChannel6;
extern lv_obj_t *ui_LabelChannel6;
extern lv_obj_t *ui_ButtonChannel7;
extern lv_obj_t *ui_LabelChannel7;
extern lv_obj_t *ui_ButtonChannel8;
extern lv_obj_t *ui_LabelChannel8;
extern lv_obj_t *ui_ButtonChannel9;
extern lv_obj_t *ui_LabelChannel9;
extern lv_obj_t *ui_ButtonChannel10;
extern lv_obj_t *ui_LabelChannel10;
extern lv_obj_t *ui_ButtonChannel11;
extern lv_obj_t *ui_LabelChannel11;
extern lv_obj_t *ui_ButtonChannel12;
extern lv_obj_t *ui_LabelChannel12;
extern lv_obj_t *ui_ButtonChannel13;
extern lv_obj_t *ui_LabelChannel13;
extern lv_obj_t *ui_ButtonChannel14;
extern lv_obj_t *ui_LabelChannel14;
extern lv_obj_t *ui_ButtonChannel15;
extern lv_obj_t *ui_LabelChannel15;
extern lv_obj_t *ui_ButtonChannel16;
extern lv_obj_t *ui_LabelChannel16;
extern lv_obj_t *ui_ContainerSelectLayer;
extern lv_obj_t *ui_ButtonLayer1;
extern lv_obj_t *ui_LabelButtonLayer1;
extern lv_obj_t *ui_ButtonLayer2;
extern lv_obj_t *ui_LabelButtonLayer2;
extern lv_obj_t *ui_ButtonLayer3;
extern lv_obj_t *ui_LabelButtonLayer3;
extern lv_obj_t *ui_ButtonLayer4;
extern lv_obj_t *ui_LabelButtonLayer4;
extern lv_obj_t *ui_ContainerCCPage;
extern lv_obj_t *ui_ButtonPage1;
extern lv_obj_t *ui_LabelPage1;
extern lv_obj_t *ui_ButtonPage2;
extern lv_obj_t *ui_LabelPage2;
extern lv_obj_t *ui_ButtonPage3;
extern lv_obj_t *ui_LabelPage3;
extern lv_obj_t *ui_ButtonPage4;
extern lv_obj_t *ui_LabelPage4;
extern lv_obj_t *ui_ButtonPage5;
extern lv_obj_t *ui_LabelPage5;
extern lv_obj_t *ui_ButtonPage6;
extern lv_obj_t *ui_LabelPage6;
extern lv_obj_t *ui_ButtonPage7;
extern lv_obj_t *ui_LabelPage7;
extern lv_obj_t *ui_ButtonPage8;
extern lv_obj_t *ui_LabelPage8;
extern lv_obj_t *ui_Container4Enc;
void ui_event_Arc17( lv_event_t * e);
extern lv_obj_t *ui_Arc17;
extern lv_obj_t *ui_LabelValue17;
extern lv_obj_t *ui_LabelPot17;
void ui_event_Arc18( lv_event_t * e);
extern lv_obj_t *ui_Arc18;
extern lv_obj_t *ui_LabelValue18;
extern lv_obj_t *ui_LabelPot18;
void ui_event_Arc19( lv_event_t * e);
extern lv_obj_t *ui_Arc19;
extern lv_obj_t *ui_LabelValue19;
extern lv_obj_t *ui_LabelPot19;
void ui_event_Arc20( lv_event_t * e);
extern lv_obj_t *ui_Arc20;
extern lv_obj_t *ui_LabelPot20;
extern lv_obj_t *ui_LabelValue20;
void ui_event_ContainerRowBottom( lv_event_t * e);
extern lv_obj_t *ui_ContainerRowBottom;
void ui_event_SwitchLFOCC( lv_event_t * e);
extern lv_obj_t *ui_SwitchLFOCC;
extern lv_obj_t *ui_LabelSwitchLFOCC1;
extern lv_obj_t *ui_ButtonLFO1;
extern lv_obj_t *ui_ButtonSettings1;
extern lv_obj_t *ui_LabelButtonSettings1;
extern lv_obj_t *ui_ButtonLFO2;
extern lv_obj_t *ui_ButtonSettings2;
extern lv_obj_t *ui_LabelButtonSettings2;
extern lv_obj_t *ui_ButtonLFO3;
extern lv_obj_t *ui_ButtonSettings3;
extern lv_obj_t *ui_LabelButtonSettings3;
extern lv_obj_t *ui_ButtonLFO4;
extern lv_obj_t *ui_ButtonSettings4;
extern lv_obj_t *ui_LabelButtonSettings4;
extern lv_obj_t *ui_LabelKillLFO;
extern lv_obj_t *ui_SwitchKillLFO;
void ui_event_RollerSettings( lv_event_t * e);
extern lv_obj_t *ui_RollerSettings;
extern lv_obj_t *ui_ButtonLFOMix;
extern lv_obj_t *ui_LabelButtonLFOMix;
extern lv_obj_t *ui_ContainerSelect;
extern lv_obj_t *ui_ButtonGeneral1;
extern lv_obj_t *ui_LabelButtonGeneral1;
extern lv_obj_t *ui_ButtonGeneral2;
extern lv_obj_t *ui_LabelButtonGeneral2;
extern lv_obj_t *ui_ButtonGeneral3;
extern lv_obj_t *ui_LabelButtonGeneral3;
extern lv_obj_t *ui_ButtonGeneral4;
extern lv_obj_t *ui_LabelButtonGeneral4;
extern lv_obj_t *ui_ContainerDisplay;
extern lv_obj_t *ui_LFODisplay;
extern lv_obj_t *ui_LabelVibration;
extern lv_obj_t *ui_SwitchVibration;
extern lv_obj_t *ui_LabelDisplay3;
extern lv_obj_t *ui_LabelDisplay4;
extern lv_obj_t *ui_ContainerPots1;
extern lv_obj_t *ui_PanelKeyboard;
extern lv_obj_t *ui_WifiRoller;
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_EditLabel;
extern lv_obj_t *ui_ButtonWifi;
extern lv_obj_t *ui_LabelWifi;
void ui_event_PanelStats( lv_event_t * e);
extern lv_obj_t *ui_PanelStats;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
