// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SC01_SquareLine

#include "../ui.h"

void ui_event_comp_ContainerPots_Arc1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC1_ARC1_LABELVALUE1], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC2_ARC2_LABELVALUE2], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC3_ARC3_LABELVALUE3], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC4_ARC4_LABELVALUE4], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC5_ARC5_LABELVALUE5], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC6_ARC6_LABELVALUE6], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC7_ARC7_LABELVALUE7], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC8_ARC8_LABELVALUE8], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC9_ARC9_LABELVALUE9], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC10_ARC10_LABELVALUE10], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC11_ARC11_LABELVALUE11], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC12_ARC12_LABELVALUE12], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC13_ARC13_LABELVALUE13], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc14( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC14_ARC14_LABELVALUE14], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc15( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC15_ARC15_LABELVALUE15], target, "", "");
}
}

void ui_event_comp_ContainerPots_Arc16( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ContainerPots = lv_event_get_user_data(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( comp_ContainerPots[UI_COMP_CONTAINERPOTS_BUTTONARC16_ARC16_LABELVALUE16], target, "", "");
}
}

// COMPONENT ContainerPots

lv_obj_t *ui_ContainerPots_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_ContainerPots;
cui_ContainerPots = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_ContainerPots);
lv_obj_set_width( cui_ContainerPots, 240);
lv_obj_set_height( cui_ContainerPots, 253);
lv_obj_set_x( cui_ContainerPots, 103 );
lv_obj_set_y( cui_ContainerPots, -31 );
lv_obj_set_align( cui_ContainerPots, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ContainerPots,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(cui_ContainerPots, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( cui_ContainerPots, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_ContainerPots, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ContainerPots, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(cui_ContainerPots, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_ContainerPots, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc1;
cui_ButtonArc1 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc1, 58);
lv_obj_set_height( cui_ButtonArc1, 58);
lv_obj_set_x( cui_ButtonArc1, -103 );
lv_obj_set_y( cui_ButtonArc1, -95 );
lv_obj_set_align( cui_ButtonArc1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc1, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc1, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc1, 100, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(cui_ButtonArc1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(cui_ButtonArc1, 255, LV_PART_MAIN| LV_STATE_DISABLED);

lv_obj_t *cui_Arc1;
cui_Arc1 = lv_arc_create(cui_ButtonArc1);
lv_obj_set_width( cui_Arc1, 60);
lv_obj_set_height( cui_Arc1, 58);
lv_obj_set_x( cui_Arc1, -102 );
lv_obj_set_y( cui_Arc1, -89 );
lv_obj_set_align( cui_Arc1, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc1, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc1, 0,127);
lv_arc_set_value(cui_Arc1, 0);
lv_obj_set_style_arc_width(cui_Arc1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc1, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc1, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc1, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc1, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc1, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc1, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue1;
cui_LabelValue1 = lv_label_create(cui_Arc1);
lv_obj_set_width( cui_LabelValue1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue1, -2 );
lv_obj_set_y( cui_LabelValue1, 18 );
lv_obj_set_align( cui_LabelValue1, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue1,"0");
lv_obj_set_style_text_font(cui_LabelValue1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot1;
cui_LabelPot1 = lv_label_create(cui_Arc1);
lv_obj_set_width( cui_LabelPot1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot1, -1 );
lv_obj_set_y( cui_LabelPot1, -1 );
lv_obj_set_align( cui_LabelPot1, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot1,"Cut \nOff");
lv_obj_set_style_text_align(cui_LabelPot1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot1, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod1;
cui_ArcMod1 = lv_arc_create(cui_Arc1);
lv_obj_set_width( cui_ArcMod1, 52);
lv_obj_set_height( cui_ArcMod1, 48);
lv_obj_set_x( cui_ArcMod1, 1 );
lv_obj_set_y( cui_ArcMod1, 0 );
lv_obj_set_align( cui_ArcMod1, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod1, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod1, 0,127);
lv_arc_set_value(cui_ArcMod1, 127);
lv_obj_set_style_arc_color(cui_ArcMod1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod1, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod1, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod1, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod1, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc2;
cui_ButtonArc2 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc2, 58);
lv_obj_set_height( cui_ButtonArc2, 58);
lv_obj_set_x( cui_ButtonArc2, -34 );
lv_obj_set_y( cui_ButtonArc2, -95 );
lv_obj_set_align( cui_ButtonArc2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc2, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc2, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc2, 100, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(cui_ButtonArc2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(cui_ButtonArc2, 255, LV_PART_MAIN| LV_STATE_DISABLED);

lv_obj_t *cui_Arc2;
cui_Arc2 = lv_arc_create(cui_ButtonArc2);
lv_obj_set_width( cui_Arc2, 60);
lv_obj_set_height( cui_Arc2, 58);
lv_obj_set_x( cui_Arc2, -102 );
lv_obj_set_y( cui_Arc2, -89 );
lv_obj_set_align( cui_Arc2, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc2, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc2, 0,127);
lv_arc_set_value(cui_Arc2, 0);
lv_obj_set_style_arc_width(cui_Arc2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc2, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc2, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc2, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc2, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc2, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc2, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue2;
cui_LabelValue2 = lv_label_create(cui_Arc2);
lv_obj_set_width( cui_LabelValue2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue2, -2 );
lv_obj_set_y( cui_LabelValue2, 18 );
lv_obj_set_align( cui_LabelValue2, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue2,"0");
lv_obj_set_style_text_font(cui_LabelValue2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot2;
cui_LabelPot2 = lv_label_create(cui_Arc2);
lv_obj_set_width( cui_LabelPot2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot2, -3 );
lv_obj_set_y( cui_LabelPot2, -1 );
lv_obj_set_align( cui_LabelPot2, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot2,"Res");
lv_obj_set_style_text_align(cui_LabelPot2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot2, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod2;
cui_ArcMod2 = lv_arc_create(cui_Arc2);
lv_obj_set_width( cui_ArcMod2, 52);
lv_obj_set_height( cui_ArcMod2, 48);
lv_obj_set_x( cui_ArcMod2, 1 );
lv_obj_set_y( cui_ArcMod2, 0 );
lv_obj_set_align( cui_ArcMod2, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod2, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod2, 0,127);
lv_arc_set_value(cui_ArcMod2, 127);
lv_obj_set_style_arc_color(cui_ArcMod2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod2, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod2, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod2, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod2, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc3;
cui_ButtonArc3 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc3, 58);
lv_obj_set_height( cui_ButtonArc3, 58);
lv_obj_set_x( cui_ButtonArc3, 34 );
lv_obj_set_y( cui_ButtonArc3, -95 );
lv_obj_set_align( cui_ButtonArc3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc3, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc3, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc3, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc3;
cui_Arc3 = lv_arc_create(cui_ButtonArc3);
lv_obj_set_width( cui_Arc3, 60);
lv_obj_set_height( cui_Arc3, 58);
lv_obj_set_x( cui_Arc3, -102 );
lv_obj_set_y( cui_Arc3, -89 );
lv_obj_set_align( cui_Arc3, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc3, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc3, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc3, 0,127);
lv_arc_set_value(cui_Arc3, 0);
lv_obj_set_style_arc_width(cui_Arc3, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc3, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc3, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc3, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc3, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc3, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc3, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc3, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue3;
cui_LabelValue3 = lv_label_create(cui_Arc3);
lv_obj_set_width( cui_LabelValue3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue3, -2 );
lv_obj_set_y( cui_LabelValue3, 18 );
lv_obj_set_align( cui_LabelValue3, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue3,"0");
lv_obj_set_style_text_font(cui_LabelValue3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot3;
cui_LabelPot3 = lv_label_create(cui_Arc3);
lv_obj_set_width( cui_LabelPot3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot3, -2 );
lv_obj_set_y( cui_LabelPot3, -5 );
lv_obj_set_align( cui_LabelPot3, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot3,"ENV\nAmount");
lv_obj_set_style_text_align(cui_LabelPot3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot3, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod3;
cui_ArcMod3 = lv_arc_create(cui_Arc3);
lv_obj_set_width( cui_ArcMod3, 52);
lv_obj_set_height( cui_ArcMod3, 48);
lv_obj_set_x( cui_ArcMod3, 1 );
lv_obj_set_y( cui_ArcMod3, 0 );
lv_obj_set_align( cui_ArcMod3, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod3, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod3, 0,127);
lv_arc_set_value(cui_ArcMod3, 127);
lv_obj_set_style_arc_color(cui_ArcMod3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod3, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod3, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod3, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod3, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod3, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc4;
cui_ButtonArc4 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc4, 58);
lv_obj_set_height( cui_ButtonArc4, 58);
lv_obj_set_x( cui_ButtonArc4, 102 );
lv_obj_set_y( cui_ButtonArc4, -96 );
lv_obj_set_align( cui_ButtonArc4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc4, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc4, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc4, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc4;
cui_Arc4 = lv_arc_create(cui_ButtonArc4);
lv_obj_set_width( cui_Arc4, 60);
lv_obj_set_height( cui_Arc4, 58);
lv_obj_set_x( cui_Arc4, -102 );
lv_obj_set_y( cui_Arc4, -89 );
lv_obj_set_align( cui_Arc4, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc4, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc4, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc4, 0,127);
lv_arc_set_value(cui_Arc4, 0);
lv_obj_set_style_arc_width(cui_Arc4, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc4, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc4, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc4, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc4, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc4, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc4, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc4, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue4;
cui_LabelValue4 = lv_label_create(cui_Arc4);
lv_obj_set_width( cui_LabelValue4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue4, -2 );
lv_obj_set_y( cui_LabelValue4, 18 );
lv_obj_set_align( cui_LabelValue4, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue4,"0");
lv_obj_set_style_text_font(cui_LabelValue4, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot4;
cui_LabelPot4 = lv_label_create(cui_Arc4);
lv_obj_set_width( cui_LabelPot4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot4, -2 );
lv_obj_set_y( cui_LabelPot4, -5 );
lv_obj_set_align( cui_LabelPot4, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot4,"LFO\nAmount");
lv_obj_set_style_text_align(cui_LabelPot4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot4, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod4;
cui_ArcMod4 = lv_arc_create(cui_Arc4);
lv_obj_set_width( cui_ArcMod4, 52);
lv_obj_set_height( cui_ArcMod4, 48);
lv_obj_set_x( cui_ArcMod4, 1 );
lv_obj_set_y( cui_ArcMod4, 0 );
lv_obj_set_align( cui_ArcMod4, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod4, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod4, 0,127);
lv_arc_set_value(cui_ArcMod4, 127);
lv_obj_set_style_arc_color(cui_ArcMod4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod4, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod4, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod4, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod4, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod4, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc5;
cui_ButtonArc5 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc5, 58);
lv_obj_set_height( cui_ButtonArc5, 58);
lv_obj_set_x( cui_ButtonArc5, -102 );
lv_obj_set_y( cui_ButtonArc5, -33 );
lv_obj_set_align( cui_ButtonArc5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc5, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc5, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc5, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc5, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc5;
cui_Arc5 = lv_arc_create(cui_ButtonArc5);
lv_obj_set_width( cui_Arc5, 60);
lv_obj_set_height( cui_Arc5, 58);
lv_obj_set_x( cui_Arc5, -102 );
lv_obj_set_y( cui_Arc5, -89 );
lv_obj_set_align( cui_Arc5, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc5, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc5, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc5, 0,127);
lv_arc_set_value(cui_Arc5, 0);
lv_obj_set_style_arc_width(cui_Arc5, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc5, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc5, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc5, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc5, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc5, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc5, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc5, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc5, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue5;
cui_LabelValue5 = lv_label_create(cui_Arc5);
lv_obj_set_width( cui_LabelValue5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue5, -2 );
lv_obj_set_y( cui_LabelValue5, 18 );
lv_obj_set_align( cui_LabelValue5, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue5,"0");
lv_obj_set_style_text_font(cui_LabelValue5, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot5;
cui_LabelPot5 = lv_label_create(cui_Arc5);
lv_obj_set_width( cui_LabelPot5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot5, -1 );
lv_obj_set_y( cui_LabelPot5, -4 );
lv_obj_set_align( cui_LabelPot5, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot5,"AMP\nAttack");
lv_obj_set_style_text_align(cui_LabelPot5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot5, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod5;
cui_ArcMod5 = lv_arc_create(cui_Arc5);
lv_obj_set_width( cui_ArcMod5, 52);
lv_obj_set_height( cui_ArcMod5, 48);
lv_obj_set_x( cui_ArcMod5, 1 );
lv_obj_set_y( cui_ArcMod5, 0 );
lv_obj_set_align( cui_ArcMod5, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod5, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod5, 0,127);
lv_arc_set_value(cui_ArcMod5, 127);
lv_obj_set_style_arc_color(cui_ArcMod5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod5, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod5, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod5, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod5, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod5, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod5, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod5, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod5, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod5, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod5, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod5, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc6;
cui_ButtonArc6 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc6, 58);
lv_obj_set_height( cui_ButtonArc6, 58);
lv_obj_set_x( cui_ButtonArc6, -35 );
lv_obj_set_y( cui_ButtonArc6, -33 );
lv_obj_set_align( cui_ButtonArc6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc6, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc6, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc6, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc6, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc6;
cui_Arc6 = lv_arc_create(cui_ButtonArc6);
lv_obj_set_width( cui_Arc6, 60);
lv_obj_set_height( cui_Arc6, 58);
lv_obj_set_x( cui_Arc6, -102 );
lv_obj_set_y( cui_Arc6, -89 );
lv_obj_set_align( cui_Arc6, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc6, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc6, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc6, 0,127);
lv_arc_set_value(cui_Arc6, 0);
lv_obj_set_style_arc_width(cui_Arc6, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc6, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc6, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc6, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc6, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc6, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc6, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc6, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc6, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc6, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc6, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue6;
cui_LabelValue6 = lv_label_create(cui_Arc6);
lv_obj_set_width( cui_LabelValue6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue6, -2 );
lv_obj_set_y( cui_LabelValue6, 18 );
lv_obj_set_align( cui_LabelValue6, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue6,"0");
lv_obj_set_style_text_font(cui_LabelValue6, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot6;
cui_LabelPot6 = lv_label_create(cui_Arc6);
lv_obj_set_width( cui_LabelPot6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot6, -1 );
lv_obj_set_y( cui_LabelPot6, -4 );
lv_obj_set_align( cui_LabelPot6, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot6,"AMP\nDecay");
lv_obj_set_style_text_align(cui_LabelPot6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot6, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod6;
cui_ArcMod6 = lv_arc_create(cui_Arc6);
lv_obj_set_width( cui_ArcMod6, 52);
lv_obj_set_height( cui_ArcMod6, 48);
lv_obj_set_x( cui_ArcMod6, 1 );
lv_obj_set_y( cui_ArcMod6, 0 );
lv_obj_set_align( cui_ArcMod6, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod6, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod6, 0,127);
lv_arc_set_value(cui_ArcMod6, 127);
lv_obj_set_style_arc_color(cui_ArcMod6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod6, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod6, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod6, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod6, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod6, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod6, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod6, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod6, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod6, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod6, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod6, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc7;
cui_ButtonArc7 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc7, 58);
lv_obj_set_height( cui_ButtonArc7, 58);
lv_obj_set_x( cui_ButtonArc7, 35 );
lv_obj_set_y( cui_ButtonArc7, -33 );
lv_obj_set_align( cui_ButtonArc7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc7, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc7, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc7, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc7;
cui_Arc7 = lv_arc_create(cui_ButtonArc7);
lv_obj_set_width( cui_Arc7, 60);
lv_obj_set_height( cui_Arc7, 58);
lv_obj_set_x( cui_Arc7, -102 );
lv_obj_set_y( cui_Arc7, -89 );
lv_obj_set_align( cui_Arc7, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc7, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc7, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc7, 0,127);
lv_arc_set_value(cui_Arc7, 0);
lv_obj_set_style_arc_width(cui_Arc7, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc7, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc7, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc7, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc7, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc7, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc7, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc7, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc7, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc7, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc7, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue7;
cui_LabelValue7 = lv_label_create(cui_Arc7);
lv_obj_set_width( cui_LabelValue7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue7, -2 );
lv_obj_set_y( cui_LabelValue7, 18 );
lv_obj_set_align( cui_LabelValue7, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue7,"0");
lv_obj_set_style_text_font(cui_LabelValue7, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot7;
cui_LabelPot7 = lv_label_create(cui_Arc7);
lv_obj_set_width( cui_LabelPot7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot7, -1 );
lv_obj_set_y( cui_LabelPot7, -4 );
lv_obj_set_align( cui_LabelPot7, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot7,"AMP\nSustain");
lv_obj_set_style_text_align(cui_LabelPot7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot7, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod7;
cui_ArcMod7 = lv_arc_create(cui_Arc7);
lv_obj_set_width( cui_ArcMod7, 52);
lv_obj_set_height( cui_ArcMod7, 48);
lv_obj_set_x( cui_ArcMod7, 1 );
lv_obj_set_y( cui_ArcMod7, 0 );
lv_obj_set_align( cui_ArcMod7, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod7, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod7, 0,127);
lv_arc_set_value(cui_ArcMod7, 127);
lv_obj_set_style_arc_color(cui_ArcMod7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod7, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod7, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod7, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod7, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod7, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod7, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod7, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod7, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod7, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod7, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc8;
cui_ButtonArc8 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc8, 58);
lv_obj_set_height( cui_ButtonArc8, 58);
lv_obj_set_x( cui_ButtonArc8, 103 );
lv_obj_set_y( cui_ButtonArc8, -32 );
lv_obj_set_align( cui_ButtonArc8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc8,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc8, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc8, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc8, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc8, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc8;
cui_Arc8 = lv_arc_create(cui_ButtonArc8);
lv_obj_set_width( cui_Arc8, 60);
lv_obj_set_height( cui_Arc8, 58);
lv_obj_set_x( cui_Arc8, -102 );
lv_obj_set_y( cui_Arc8, -89 );
lv_obj_set_align( cui_Arc8, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc8, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc8, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc8, 0,127);
lv_arc_set_value(cui_Arc8, 0);
lv_obj_set_style_arc_width(cui_Arc8, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc8, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc8, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc8, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc8, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc8, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc8, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc8, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc8, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc8, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc8, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue8;
cui_LabelValue8 = lv_label_create(cui_Arc8);
lv_obj_set_width( cui_LabelValue8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue8, -2 );
lv_obj_set_y( cui_LabelValue8, 18 );
lv_obj_set_align( cui_LabelValue8, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue8,"0");
lv_obj_set_style_text_font(cui_LabelValue8, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot8;
cui_LabelPot8 = lv_label_create(cui_Arc8);
lv_obj_set_width( cui_LabelPot8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot8, -1 );
lv_obj_set_y( cui_LabelPot8, -4 );
lv_obj_set_align( cui_LabelPot8, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot8,"AMP\nRelease");
lv_obj_set_style_text_align(cui_LabelPot8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot8, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod8;
cui_ArcMod8 = lv_arc_create(cui_Arc8);
lv_obj_set_width( cui_ArcMod8, 52);
lv_obj_set_height( cui_ArcMod8, 48);
lv_obj_set_x( cui_ArcMod8, 1 );
lv_obj_set_y( cui_ArcMod8, 0 );
lv_obj_set_align( cui_ArcMod8, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod8, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod8, 0,127);
lv_arc_set_value(cui_ArcMod8, 127);
lv_obj_set_style_arc_color(cui_ArcMod8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod8, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod8, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod8, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod8, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod8, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod8, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod8, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod8, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod8, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod8, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod8, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc9;
cui_ButtonArc9 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc9, 58);
lv_obj_set_height( cui_ButtonArc9, 58);
lv_obj_set_x( cui_ButtonArc9, -103 );
lv_obj_set_y( cui_ButtonArc9, 32 );
lv_obj_set_align( cui_ButtonArc9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc9,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc9, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc9, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc9, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc9, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc9, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc9;
cui_Arc9 = lv_arc_create(cui_ButtonArc9);
lv_obj_set_width( cui_Arc9, 60);
lv_obj_set_height( cui_Arc9, 58);
lv_obj_set_x( cui_Arc9, -102 );
lv_obj_set_y( cui_Arc9, -89 );
lv_obj_set_align( cui_Arc9, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc9, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc9, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc9, 0,127);
lv_arc_set_value(cui_Arc9, 0);
lv_obj_set_style_arc_width(cui_Arc9, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc9, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc9, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc9, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc9, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc9, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc9, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc9, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc9, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc9, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc9, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue9;
cui_LabelValue9 = lv_label_create(cui_Arc9);
lv_obj_set_width( cui_LabelValue9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue9, -2 );
lv_obj_set_y( cui_LabelValue9, 18 );
lv_obj_set_align( cui_LabelValue9, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue9,"0");
lv_obj_set_style_text_font(cui_LabelValue9, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot9;
cui_LabelPot9 = lv_label_create(cui_Arc9);
lv_obj_set_width( cui_LabelPot9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot9, -3 );
lv_obj_set_y( cui_LabelPot9, -1 );
lv_obj_set_align( cui_LabelPot9, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot9,"FILT\nAttack");
lv_obj_set_style_text_align(cui_LabelPot9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot9, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod9;
cui_ArcMod9 = lv_arc_create(cui_Arc9);
lv_obj_set_width( cui_ArcMod9, 52);
lv_obj_set_height( cui_ArcMod9, 48);
lv_obj_set_x( cui_ArcMod9, 1 );
lv_obj_set_y( cui_ArcMod9, 0 );
lv_obj_set_align( cui_ArcMod9, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod9, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod9, 0,127);
lv_arc_set_value(cui_ArcMod9, 127);
lv_obj_set_style_arc_color(cui_ArcMod9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod9, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod9, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod9, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod9, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod9, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod9, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod9, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod9, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod9, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod9, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod9, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc10;
cui_ButtonArc10 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc10, 58);
lv_obj_set_height( cui_ButtonArc10, 58);
lv_obj_set_x( cui_ButtonArc10, -34 );
lv_obj_set_y( cui_ButtonArc10, 32 );
lv_obj_set_align( cui_ButtonArc10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc10,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc10, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc10, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc10, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc10, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc10, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc10;
cui_Arc10 = lv_arc_create(cui_ButtonArc10);
lv_obj_set_width( cui_Arc10, 60);
lv_obj_set_height( cui_Arc10, 58);
lv_obj_set_x( cui_Arc10, -102 );
lv_obj_set_y( cui_Arc10, -89 );
lv_obj_set_align( cui_Arc10, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc10, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc10, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc10, 0,127);
lv_arc_set_value(cui_Arc10, 0);
lv_obj_set_style_arc_width(cui_Arc10, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc10, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc10, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc10, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc10, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc10, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc10, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc10, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc10, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc10, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc10, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue10;
cui_LabelValue10 = lv_label_create(cui_Arc10);
lv_obj_set_width( cui_LabelValue10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue10, -2 );
lv_obj_set_y( cui_LabelValue10, 18 );
lv_obj_set_align( cui_LabelValue10, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue10,"0");
lv_obj_set_style_text_font(cui_LabelValue10, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot10;
cui_LabelPot10 = lv_label_create(cui_Arc10);
lv_obj_set_width( cui_LabelPot10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot10, -1 );
lv_obj_set_y( cui_LabelPot10, -4 );
lv_obj_set_align( cui_LabelPot10, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot10,"FILT\nDecay");
lv_obj_set_style_text_align(cui_LabelPot10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot10, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod10;
cui_ArcMod10 = lv_arc_create(cui_Arc10);
lv_obj_set_width( cui_ArcMod10, 52);
lv_obj_set_height( cui_ArcMod10, 48);
lv_obj_set_x( cui_ArcMod10, 1 );
lv_obj_set_y( cui_ArcMod10, 0 );
lv_obj_set_align( cui_ArcMod10, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod10, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod10, 0,127);
lv_arc_set_value(cui_ArcMod10, 127);
lv_obj_set_style_arc_color(cui_ArcMod10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod10, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod10, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod10, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod10, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod10, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod10, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod10, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod10, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod10, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod10, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod10, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc11;
cui_ButtonArc11 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc11, 58);
lv_obj_set_height( cui_ButtonArc11, 58);
lv_obj_set_x( cui_ButtonArc11, 35 );
lv_obj_set_y( cui_ButtonArc11, 33 );
lv_obj_set_align( cui_ButtonArc11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc11,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc11, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc11, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc11, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc11, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc11, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc11, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc11;
cui_Arc11 = lv_arc_create(cui_ButtonArc11);
lv_obj_set_width( cui_Arc11, 60);
lv_obj_set_height( cui_Arc11, 58);
lv_obj_set_x( cui_Arc11, -102 );
lv_obj_set_y( cui_Arc11, -89 );
lv_obj_set_align( cui_Arc11, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc11, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc11, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc11, 0,127);
lv_arc_set_value(cui_Arc11, 0);
lv_obj_set_style_arc_width(cui_Arc11, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc11, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc11, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc11, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc11, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc11, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc11, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc11, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc11, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc11, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc11, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue11;
cui_LabelValue11 = lv_label_create(cui_Arc11);
lv_obj_set_width( cui_LabelValue11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue11, -2 );
lv_obj_set_y( cui_LabelValue11, 18 );
lv_obj_set_align( cui_LabelValue11, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue11,"0");
lv_obj_set_style_text_font(cui_LabelValue11, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot11;
cui_LabelPot11 = lv_label_create(cui_Arc11);
lv_obj_set_width( cui_LabelPot11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot11, -1 );
lv_obj_set_y( cui_LabelPot11, -4 );
lv_obj_set_align( cui_LabelPot11, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot11,"FILT\nSustain");
lv_obj_set_style_text_align(cui_LabelPot11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot11, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod11;
cui_ArcMod11 = lv_arc_create(cui_Arc11);
lv_obj_set_width( cui_ArcMod11, 52);
lv_obj_set_height( cui_ArcMod11, 48);
lv_obj_set_x( cui_ArcMod11, 1 );
lv_obj_set_y( cui_ArcMod11, 0 );
lv_obj_set_align( cui_ArcMod11, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod11, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod11, 0,127);
lv_arc_set_value(cui_ArcMod11, 127);
lv_obj_set_style_arc_color(cui_ArcMod11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod11, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod11, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod11, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod11, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod11, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod11, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod11, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod11, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod11, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod11, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod11, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc12;
cui_ButtonArc12 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc12, 58);
lv_obj_set_height( cui_ButtonArc12, 58);
lv_obj_set_x( cui_ButtonArc12, 103 );
lv_obj_set_y( cui_ButtonArc12, 33 );
lv_obj_set_align( cui_ButtonArc12, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc12, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc12, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc12, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc12, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc12, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc12, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc12;
cui_Arc12 = lv_arc_create(cui_ButtonArc12);
lv_obj_set_width( cui_Arc12, 60);
lv_obj_set_height( cui_Arc12, 58);
lv_obj_set_x( cui_Arc12, -102 );
lv_obj_set_y( cui_Arc12, -89 );
lv_obj_set_align( cui_Arc12, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc12, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc12, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc12, 0,127);
lv_arc_set_value(cui_Arc12, 0);
lv_obj_set_style_arc_width(cui_Arc12, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc12, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc12, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc12, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc12, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc12, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc12, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc12, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc12, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc12, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc12, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue12;
cui_LabelValue12 = lv_label_create(cui_Arc12);
lv_obj_set_width( cui_LabelValue12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue12, -2 );
lv_obj_set_y( cui_LabelValue12, 18 );
lv_obj_set_align( cui_LabelValue12, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue12,"0");
lv_obj_set_style_text_font(cui_LabelValue12, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot12;
cui_LabelPot12 = lv_label_create(cui_Arc12);
lv_obj_set_width( cui_LabelPot12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot12, -1 );
lv_obj_set_y( cui_LabelPot12, -4 );
lv_obj_set_align( cui_LabelPot12, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot12,"FILT\nRelease");
lv_obj_set_style_text_align(cui_LabelPot12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot12, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod12;
cui_ArcMod12 = lv_arc_create(cui_Arc12);
lv_obj_set_width( cui_ArcMod12, 52);
lv_obj_set_height( cui_ArcMod12, 48);
lv_obj_set_x( cui_ArcMod12, 1 );
lv_obj_set_y( cui_ArcMod12, 0 );
lv_obj_set_align( cui_ArcMod12, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod12, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod12, 0,127);
lv_arc_set_value(cui_ArcMod12, 127);
lv_obj_set_style_arc_color(cui_ArcMod12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod12, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod12, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod12, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod12, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod12, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod12, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod12, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod12, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod12, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod12, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod12, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc13;
cui_ButtonArc13 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc13, 58);
lv_obj_set_height( cui_ButtonArc13, 58);
lv_obj_set_x( cui_ButtonArc13, -102 );
lv_obj_set_y( cui_ButtonArc13, 96 );
lv_obj_set_align( cui_ButtonArc13, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc13,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc13, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc13, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc13, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc13, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc13, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc13, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc13;
cui_Arc13 = lv_arc_create(cui_ButtonArc13);
lv_obj_set_width( cui_Arc13, 60);
lv_obj_set_height( cui_Arc13, 58);
lv_obj_set_x( cui_Arc13, -102 );
lv_obj_set_y( cui_Arc13, -89 );
lv_obj_set_align( cui_Arc13, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc13, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc13, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc13, 0,127);
lv_arc_set_value(cui_Arc13, 0);
lv_obj_set_style_arc_width(cui_Arc13, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc13, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc13, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc13, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc13, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc13, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc13, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc13, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc13, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc13, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc13, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue13;
cui_LabelValue13 = lv_label_create(cui_Arc13);
lv_obj_set_width( cui_LabelValue13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue13, -2 );
lv_obj_set_y( cui_LabelValue13, 18 );
lv_obj_set_align( cui_LabelValue13, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue13,"0");
lv_obj_set_style_text_font(cui_LabelValue13, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot13;
cui_LabelPot13 = lv_label_create(cui_Arc13);
lv_obj_set_width( cui_LabelPot13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot13, -1 );
lv_obj_set_y( cui_LabelPot13, 0 );
lv_obj_set_align( cui_LabelPot13, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot13,"Send\nA");
lv_obj_set_style_text_align(cui_LabelPot13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot13, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod13;
cui_ArcMod13 = lv_arc_create(cui_Arc13);
lv_obj_set_width( cui_ArcMod13, 52);
lv_obj_set_height( cui_ArcMod13, 48);
lv_obj_set_x( cui_ArcMod13, 1 );
lv_obj_set_y( cui_ArcMod13, 0 );
lv_obj_set_align( cui_ArcMod13, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod13, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod13, 0,127);
lv_arc_set_value(cui_ArcMod13, 127);
lv_obj_set_style_arc_color(cui_ArcMod13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod13, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod13, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod13, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod13, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod13, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod13, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod13, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod13, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod13, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod13, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod13, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc14;
cui_ButtonArc14 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc14, 58);
lv_obj_set_height( cui_ButtonArc14, 58);
lv_obj_set_x( cui_ButtonArc14, -35 );
lv_obj_set_y( cui_ButtonArc14, 95 );
lv_obj_set_align( cui_ButtonArc14, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc14,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc14, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc14, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc14, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc14, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc14, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc14, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc14;
cui_Arc14 = lv_arc_create(cui_ButtonArc14);
lv_obj_set_width( cui_Arc14, 60);
lv_obj_set_height( cui_Arc14, 58);
lv_obj_set_x( cui_Arc14, -102 );
lv_obj_set_y( cui_Arc14, -89 );
lv_obj_set_align( cui_Arc14, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc14, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc14, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc14, 0,127);
lv_arc_set_value(cui_Arc14, 0);
lv_obj_set_style_arc_width(cui_Arc14, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc14, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc14, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc14, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc14, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc14, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc14, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc14, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc14, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc14, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc14, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue14;
cui_LabelValue14 = lv_label_create(cui_Arc14);
lv_obj_set_width( cui_LabelValue14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue14, -2 );
lv_obj_set_y( cui_LabelValue14, 18 );
lv_obj_set_align( cui_LabelValue14, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue14,"0");
lv_obj_set_style_text_font(cui_LabelValue14, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot14;
cui_LabelPot14 = lv_label_create(cui_Arc14);
lv_obj_set_width( cui_LabelPot14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot14, -1 );
lv_obj_set_y( cui_LabelPot14, 0 );
lv_obj_set_align( cui_LabelPot14, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot14,"Send\nB");
lv_obj_set_style_text_align(cui_LabelPot14, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot14, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod14;
cui_ArcMod14 = lv_arc_create(cui_Arc14);
lv_obj_set_width( cui_ArcMod14, 52);
lv_obj_set_height( cui_ArcMod14, 48);
lv_obj_set_x( cui_ArcMod14, 1 );
lv_obj_set_y( cui_ArcMod14, 0 );
lv_obj_set_align( cui_ArcMod14, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod14, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod14, 0,127);
lv_arc_set_value(cui_ArcMod14, 127);
lv_obj_set_style_arc_color(cui_ArcMod14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod14, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod14, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod14, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod14, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod14, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod14, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod14, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod14, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod14, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod14, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod14, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc15;
cui_ButtonArc15 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc15, 58);
lv_obj_set_height( cui_ButtonArc15, 58);
lv_obj_set_x( cui_ButtonArc15, 34 );
lv_obj_set_y( cui_ButtonArc15, 95 );
lv_obj_set_align( cui_ButtonArc15, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc15,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc15, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc15, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc15, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc15, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc15, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc15, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc15;
cui_Arc15 = lv_arc_create(cui_ButtonArc15);
lv_obj_set_width( cui_Arc15, 60);
lv_obj_set_height( cui_Arc15, 58);
lv_obj_set_x( cui_Arc15, -102 );
lv_obj_set_y( cui_Arc15, -89 );
lv_obj_set_align( cui_Arc15, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc15, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc15, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc15, 0,127);
lv_arc_set_value(cui_Arc15, 0);
lv_obj_set_style_arc_width(cui_Arc15, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc15, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc15, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc15, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc15, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc15, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc15, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc15, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc15, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc15, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc15, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue15;
cui_LabelValue15 = lv_label_create(cui_Arc15);
lv_obj_set_width( cui_LabelValue15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue15, -2 );
lv_obj_set_y( cui_LabelValue15, 18 );
lv_obj_set_align( cui_LabelValue15, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue15,"0");
lv_obj_set_style_text_font(cui_LabelValue15, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot15;
cui_LabelPot15 = lv_label_create(cui_Arc15);
lv_obj_set_width( cui_LabelPot15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot15, -1 );
lv_obj_set_y( cui_LabelPot15, 0 );
lv_obj_set_align( cui_LabelPot15, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot15,"Send\nC");
lv_obj_set_style_text_align(cui_LabelPot15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot15, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod15;
cui_ArcMod15 = lv_arc_create(cui_Arc15);
lv_obj_set_width( cui_ArcMod15, 52);
lv_obj_set_height( cui_ArcMod15, 48);
lv_obj_set_x( cui_ArcMod15, 1 );
lv_obj_set_y( cui_ArcMod15, 0 );
lv_obj_set_align( cui_ArcMod15, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod15, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod15, 0,127);
lv_arc_set_value(cui_ArcMod15, 127);
lv_obj_set_style_arc_color(cui_ArcMod15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod15, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod15, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod15, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod15, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod15, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod15, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod15, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod15, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod15, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod15, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod15, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_ButtonArc16;
cui_ButtonArc16 = lv_btn_create(cui_ContainerPots);
lv_obj_set_width( cui_ButtonArc16, 58);
lv_obj_set_height( cui_ButtonArc16, 58);
lv_obj_set_x( cui_ButtonArc16, 103 );
lv_obj_set_y( cui_ButtonArc16, 96 );
lv_obj_set_align( cui_ButtonArc16, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ButtonArc16,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ButtonArc16, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
lv_obj_clear_flag( cui_ButtonArc16, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_bg_color(cui_ButtonArc16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ButtonArc16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ButtonArc16, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ButtonArc16, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ButtonArc16, 11, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ButtonArc16, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ButtonArc16, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(cui_ButtonArc16, 100, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_t *cui_Arc16;
cui_Arc16 = lv_arc_create(cui_ButtonArc16);
lv_obj_set_width( cui_Arc16, 60);
lv_obj_set_height( cui_Arc16, 58);
lv_obj_set_x( cui_Arc16, -102 );
lv_obj_set_y( cui_Arc16, -89 );
lv_obj_set_align( cui_Arc16, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_Arc16, LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( cui_Arc16, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_range(cui_Arc16, 0,127);
lv_arc_set_value(cui_Arc16, 0);
lv_obj_set_style_arc_width(cui_Arc16, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_Arc16, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_Arc16, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_Arc16, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_Arc16, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_Arc16, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_Arc16, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Arc16, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Arc16, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Arc16, -1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Arc16, -1, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelValue16;
cui_LabelValue16 = lv_label_create(cui_Arc16);
lv_obj_set_width( cui_LabelValue16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelValue16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelValue16, -2 );
lv_obj_set_y( cui_LabelValue16, 18 );
lv_obj_set_align( cui_LabelValue16, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelValue16,"0");
lv_obj_set_style_text_font(cui_LabelValue16, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_LabelPot16;
cui_LabelPot16 = lv_label_create(cui_Arc16);
lv_obj_set_width( cui_LabelPot16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_LabelPot16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_LabelPot16, -2 );
lv_obj_set_y( cui_LabelPot16, -1 );
lv_obj_set_align( cui_LabelPot16, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelPot16,"Volume");
lv_obj_set_style_text_align(cui_LabelPot16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_LabelPot16, &lv_font_montserrat_8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ArcMod16;
cui_ArcMod16 = lv_arc_create(cui_Arc16);
lv_obj_set_width( cui_ArcMod16, 52);
lv_obj_set_height( cui_ArcMod16, 48);
lv_obj_set_x( cui_ArcMod16, 1 );
lv_obj_set_y( cui_ArcMod16, 0 );
lv_obj_set_align( cui_ArcMod16, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_ArcMod16, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(cui_ArcMod16, 0,127);
lv_arc_set_value(cui_ArcMod16, 127);
lv_obj_set_style_arc_color(cui_ArcMod16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod16, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(cui_ArcMod16, lv_color_hex(0xA1C9FB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(cui_ArcMod16, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(cui_ArcMod16, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(cui_ArcMod16, 100, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_ArcMod16, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ArcMod16, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ArcMod16, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ArcMod16, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ArcMod16, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ArcMod16, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERPOTS_NUM);
children[UI_COMP_CONTAINERPOTS_CONTAINERPOTS] = cui_ContainerPots;
children[UI_COMP_CONTAINERPOTS_BUTTONARC1] = cui_ButtonArc1;
children[UI_COMP_CONTAINERPOTS_BUTTONARC1_ARC1] = cui_Arc1;
children[UI_COMP_CONTAINERPOTS_BUTTONARC1_ARC1_LABELVALUE1] = cui_LabelValue1;
children[UI_COMP_CONTAINERPOTS_BUTTONARC1_ARC1_LABELPOT1] = cui_LabelPot1;
children[UI_COMP_CONTAINERPOTS_BUTTONARC1_ARC1_ARCMOD1] = cui_ArcMod1;
children[UI_COMP_CONTAINERPOTS_BUTTONARC2] = cui_ButtonArc2;
children[UI_COMP_CONTAINERPOTS_BUTTONARC2_ARC2] = cui_Arc2;
children[UI_COMP_CONTAINERPOTS_BUTTONARC2_ARC2_LABELVALUE2] = cui_LabelValue2;
children[UI_COMP_CONTAINERPOTS_BUTTONARC2_ARC2_LABELPOT2] = cui_LabelPot2;
children[UI_COMP_CONTAINERPOTS_BUTTONARC2_ARC2_ARCMOD2] = cui_ArcMod2;
children[UI_COMP_CONTAINERPOTS_BUTTONARC3] = cui_ButtonArc3;
children[UI_COMP_CONTAINERPOTS_BUTTONARC3_ARC3] = cui_Arc3;
children[UI_COMP_CONTAINERPOTS_BUTTONARC3_ARC3_LABELVALUE3] = cui_LabelValue3;
children[UI_COMP_CONTAINERPOTS_BUTTONARC3_ARC3_LABELPOT3] = cui_LabelPot3;
children[UI_COMP_CONTAINERPOTS_BUTTONARC3_ARC3_ARCMOD3] = cui_ArcMod3;
children[UI_COMP_CONTAINERPOTS_BUTTONARC4] = cui_ButtonArc4;
children[UI_COMP_CONTAINERPOTS_BUTTONARC4_ARC4] = cui_Arc4;
children[UI_COMP_CONTAINERPOTS_BUTTONARC4_ARC4_LABELVALUE4] = cui_LabelValue4;
children[UI_COMP_CONTAINERPOTS_BUTTONARC4_ARC4_LABELPOT4] = cui_LabelPot4;
children[UI_COMP_CONTAINERPOTS_BUTTONARC4_ARC4_ARCMOD4] = cui_ArcMod4;
children[UI_COMP_CONTAINERPOTS_BUTTONARC5] = cui_ButtonArc5;
children[UI_COMP_CONTAINERPOTS_BUTTONARC5_ARC5] = cui_Arc5;
children[UI_COMP_CONTAINERPOTS_BUTTONARC5_ARC5_LABELVALUE5] = cui_LabelValue5;
children[UI_COMP_CONTAINERPOTS_BUTTONARC5_ARC5_LABELPOT5] = cui_LabelPot5;
children[UI_COMP_CONTAINERPOTS_BUTTONARC5_ARC5_ARCMOD5] = cui_ArcMod5;
children[UI_COMP_CONTAINERPOTS_BUTTONARC6] = cui_ButtonArc6;
children[UI_COMP_CONTAINERPOTS_BUTTONARC6_ARC6] = cui_Arc6;
children[UI_COMP_CONTAINERPOTS_BUTTONARC6_ARC6_LABELVALUE6] = cui_LabelValue6;
children[UI_COMP_CONTAINERPOTS_BUTTONARC6_ARC6_LABELPOT6] = cui_LabelPot6;
children[UI_COMP_CONTAINERPOTS_BUTTONARC6_ARC6_ARCMOD6] = cui_ArcMod6;
children[UI_COMP_CONTAINERPOTS_BUTTONARC7] = cui_ButtonArc7;
children[UI_COMP_CONTAINERPOTS_BUTTONARC7_ARC7] = cui_Arc7;
children[UI_COMP_CONTAINERPOTS_BUTTONARC7_ARC7_LABELVALUE7] = cui_LabelValue7;
children[UI_COMP_CONTAINERPOTS_BUTTONARC7_ARC7_LABELPOT7] = cui_LabelPot7;
children[UI_COMP_CONTAINERPOTS_BUTTONARC7_ARC7_ARCMOD7] = cui_ArcMod7;
children[UI_COMP_CONTAINERPOTS_BUTTONARC8] = cui_ButtonArc8;
children[UI_COMP_CONTAINERPOTS_BUTTONARC8_ARC8] = cui_Arc8;
children[UI_COMP_CONTAINERPOTS_BUTTONARC8_ARC8_LABELVALUE8] = cui_LabelValue8;
children[UI_COMP_CONTAINERPOTS_BUTTONARC8_ARC8_LABELPOT8] = cui_LabelPot8;
children[UI_COMP_CONTAINERPOTS_BUTTONARC8_ARC8_ARCMOD8] = cui_ArcMod8;
children[UI_COMP_CONTAINERPOTS_BUTTONARC9] = cui_ButtonArc9;
children[UI_COMP_CONTAINERPOTS_BUTTONARC9_ARC9] = cui_Arc9;
children[UI_COMP_CONTAINERPOTS_BUTTONARC9_ARC9_LABELVALUE9] = cui_LabelValue9;
children[UI_COMP_CONTAINERPOTS_BUTTONARC9_ARC9_LABELPOT9] = cui_LabelPot9;
children[UI_COMP_CONTAINERPOTS_BUTTONARC9_ARC9_ARCMOD9] = cui_ArcMod9;
children[UI_COMP_CONTAINERPOTS_BUTTONARC10] = cui_ButtonArc10;
children[UI_COMP_CONTAINERPOTS_BUTTONARC10_ARC10] = cui_Arc10;
children[UI_COMP_CONTAINERPOTS_BUTTONARC10_ARC10_LABELVALUE10] = cui_LabelValue10;
children[UI_COMP_CONTAINERPOTS_BUTTONARC10_ARC10_LABELPOT10] = cui_LabelPot10;
children[UI_COMP_CONTAINERPOTS_BUTTONARC10_ARC10_ARCMOD10] = cui_ArcMod10;
children[UI_COMP_CONTAINERPOTS_BUTTONARC11] = cui_ButtonArc11;
children[UI_COMP_CONTAINERPOTS_BUTTONARC11_ARC11] = cui_Arc11;
children[UI_COMP_CONTAINERPOTS_BUTTONARC11_ARC11_LABELVALUE11] = cui_LabelValue11;
children[UI_COMP_CONTAINERPOTS_BUTTONARC11_ARC11_LABELPOT11] = cui_LabelPot11;
children[UI_COMP_CONTAINERPOTS_BUTTONARC11_ARC11_ARCMOD11] = cui_ArcMod11;
children[UI_COMP_CONTAINERPOTS_BUTTONARC12] = cui_ButtonArc12;
children[UI_COMP_CONTAINERPOTS_BUTTONARC12_ARC12] = cui_Arc12;
children[UI_COMP_CONTAINERPOTS_BUTTONARC12_ARC12_LABELVALUE12] = cui_LabelValue12;
children[UI_COMP_CONTAINERPOTS_BUTTONARC12_ARC12_LABELPOT12] = cui_LabelPot12;
children[UI_COMP_CONTAINERPOTS_BUTTONARC12_ARC12_ARCMOD12] = cui_ArcMod12;
children[UI_COMP_CONTAINERPOTS_BUTTONARC13] = cui_ButtonArc13;
children[UI_COMP_CONTAINERPOTS_BUTTONARC13_ARC13] = cui_Arc13;
children[UI_COMP_CONTAINERPOTS_BUTTONARC13_ARC13_LABELVALUE13] = cui_LabelValue13;
children[UI_COMP_CONTAINERPOTS_BUTTONARC13_ARC13_LABELPOT13] = cui_LabelPot13;
children[UI_COMP_CONTAINERPOTS_BUTTONARC13_ARC13_ARCMOD13] = cui_ArcMod13;
children[UI_COMP_CONTAINERPOTS_BUTTONARC14] = cui_ButtonArc14;
children[UI_COMP_CONTAINERPOTS_BUTTONARC14_ARC14] = cui_Arc14;
children[UI_COMP_CONTAINERPOTS_BUTTONARC14_ARC14_LABELVALUE14] = cui_LabelValue14;
children[UI_COMP_CONTAINERPOTS_BUTTONARC14_ARC14_LABELPOT14] = cui_LabelPot14;
children[UI_COMP_CONTAINERPOTS_BUTTONARC14_ARC14_ARCMOD14] = cui_ArcMod14;
children[UI_COMP_CONTAINERPOTS_BUTTONARC15] = cui_ButtonArc15;
children[UI_COMP_CONTAINERPOTS_BUTTONARC15_ARC15] = cui_Arc15;
children[UI_COMP_CONTAINERPOTS_BUTTONARC15_ARC15_LABELVALUE15] = cui_LabelValue15;
children[UI_COMP_CONTAINERPOTS_BUTTONARC15_ARC15_LABELPOT15] = cui_LabelPot15;
children[UI_COMP_CONTAINERPOTS_BUTTONARC15_ARC15_ARCMOD15] = cui_ArcMod15;
children[UI_COMP_CONTAINERPOTS_BUTTONARC16] = cui_ButtonArc16;
children[UI_COMP_CONTAINERPOTS_BUTTONARC16_ARC16] = cui_Arc16;
children[UI_COMP_CONTAINERPOTS_BUTTONARC16_ARC16_LABELVALUE16] = cui_LabelValue16;
children[UI_COMP_CONTAINERPOTS_BUTTONARC16_ARC16_LABELPOT16] = cui_LabelPot16;
children[UI_COMP_CONTAINERPOTS_BUTTONARC16_ARC16_ARCMOD16] = cui_ArcMod16;
lv_obj_add_event_cb(cui_ContainerPots, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_ContainerPots, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_Arc1, ui_event_comp_ContainerPots_Arc1, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc2, ui_event_comp_ContainerPots_Arc2, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc3, ui_event_comp_ContainerPots_Arc3, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc4, ui_event_comp_ContainerPots_Arc4, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc5, ui_event_comp_ContainerPots_Arc5, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc6, ui_event_comp_ContainerPots_Arc6, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc7, ui_event_comp_ContainerPots_Arc7, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc8, ui_event_comp_ContainerPots_Arc8, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc9, ui_event_comp_ContainerPots_Arc9, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc10, ui_event_comp_ContainerPots_Arc10, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc11, ui_event_comp_ContainerPots_Arc11, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc12, ui_event_comp_ContainerPots_Arc12, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc13, ui_event_comp_ContainerPots_Arc13, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc14, ui_event_comp_ContainerPots_Arc14, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc15, ui_event_comp_ContainerPots_Arc15, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_Arc16, ui_event_comp_ContainerPots_Arc16, LV_EVENT_ALL, children);
ui_comp_ContainerPots_create_hook(cui_ContainerPots);
return cui_ContainerPots; 
}

