// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SC01_SquareLine

#include "../ui.h"

void ui_comp_ContainerPots_create_hook( lv_obj_t * comp)
{
}
